language: go

go: 1.3

install:
  - git config --global user.email "a@a.com"
  - git config --global user.name "a"

  # install libgit2
  - sudo apt-get install -qy cmake
  - wget -O /tmp/libgit2.tgz https://github.com/libgit2/libgit2/tarball/e18d5e52e385c0cc2ad8d9d4fdd545517f170a11
  - cd /tmp && tar xzf /tmp/libgit2.tgz && cd /tmp/libgit2-libgit2-e18d5e5 && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CLAR=OFF -DTHREADSAFE=ON && sudo cmake --build . --target install

  - cd $TRAVIS_BUILD_DIR

  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - go get -v -u github.com/kr/godep

script:
  - go list ./... | grep -v cluster | xargs godep go test
